import Contato from '@/components/sections/Contato'
import Principal from '@/components/sections/Principal'
import Projects from '@/components/sections/Projects'
import Skills from '@/components/sections/Skills'
import Sobre from '@/components/sections/Sobre'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Página Principal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Principal />
      <Sobre />
      <Skills />
      <Projects />
      <Contato />
    </>
  )
}
